// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: proto/weather.proto

package proto

import (
	fmt "fmt"
	_ "github.com/gogo/protobuf/gogoproto"
	proto "github.com/gogo/protobuf/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type ForecastRequest struct {
	Location string `protobuf:"bytes,1,opt,name=Location,json=location,proto3" json:"location,omitempty"`
	Duration string `protobuf:"bytes,2,opt,name=Duration,json=duration,proto3" json:"duration,omitempty"`
}

func (m *ForecastRequest) Reset()         { *m = ForecastRequest{} }
func (m *ForecastRequest) String() string { return proto.CompactTextString(m) }
func (*ForecastRequest) ProtoMessage()    {}
func (*ForecastRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_ecdc6c2fb8d35c9c, []int{0}
}
func (m *ForecastRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *ForecastRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_ForecastRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *ForecastRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ForecastRequest.Merge(m, src)
}
func (m *ForecastRequest) XXX_Size() int {
	return m.Size()
}
func (m *ForecastRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ForecastRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ForecastRequest proto.InternalMessageInfo

func (m *ForecastRequest) GetLocation() string {
	if m != nil {
		return m.Location
	}
	return ""
}

func (m *ForecastRequest) GetDuration() string {
	if m != nil {
		return m.Duration
	}
	return ""
}

type ForecastResponse struct {
	Result string `protobuf:"bytes,1,opt,name=Result,json=result,proto3" json:"result,omitempty"`
}

func (m *ForecastResponse) Reset()         { *m = ForecastResponse{} }
func (m *ForecastResponse) String() string { return proto.CompactTextString(m) }
func (*ForecastResponse) ProtoMessage()    {}
func (*ForecastResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_ecdc6c2fb8d35c9c, []int{1}
}
func (m *ForecastResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *ForecastResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_ForecastResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *ForecastResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ForecastResponse.Merge(m, src)
}
func (m *ForecastResponse) XXX_Size() int {
	return m.Size()
}
func (m *ForecastResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ForecastResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ForecastResponse proto.InternalMessageInfo

func (m *ForecastResponse) GetResult() string {
	if m != nil {
		return m.Result
	}
	return ""
}

type NowRequest struct {
	Location string `protobuf:"bytes,1,opt,name=Location,json=location,proto3" json:"location,omitempty"`
}

func (m *NowRequest) Reset()         { *m = NowRequest{} }
func (m *NowRequest) String() string { return proto.CompactTextString(m) }
func (*NowRequest) ProtoMessage()    {}
func (*NowRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_ecdc6c2fb8d35c9c, []int{2}
}
func (m *NowRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *NowRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_NowRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *NowRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NowRequest.Merge(m, src)
}
func (m *NowRequest) XXX_Size() int {
	return m.Size()
}
func (m *NowRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_NowRequest.DiscardUnknown(m)
}

var xxx_messageInfo_NowRequest proto.InternalMessageInfo

func (m *NowRequest) GetLocation() string {
	if m != nil {
		return m.Location
	}
	return ""
}

type NowResponse struct {
	Result string `protobuf:"bytes,1,opt,name=Result,json=result,proto3" json:"result,omitempty"`
}

func (m *NowResponse) Reset()         { *m = NowResponse{} }
func (m *NowResponse) String() string { return proto.CompactTextString(m) }
func (*NowResponse) ProtoMessage()    {}
func (*NowResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_ecdc6c2fb8d35c9c, []int{3}
}
func (m *NowResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *NowResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_NowResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *NowResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NowResponse.Merge(m, src)
}
func (m *NowResponse) XXX_Size() int {
	return m.Size()
}
func (m *NowResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_NowResponse.DiscardUnknown(m)
}

var xxx_messageInfo_NowResponse proto.InternalMessageInfo

func (m *NowResponse) GetResult() string {
	if m != nil {
		return m.Result
	}
	return ""
}

type IndicesRequest struct {
	Location string `protobuf:"bytes,1,opt,name=Location,json=location,proto3" json:"location,omitempty"`
	Type     string `protobuf:"bytes,2,opt,name=Type,json=type,proto3" json:"type,omitempty"`
	Duration string `protobuf:"bytes,3,opt,name=Duration,json=duration,proto3" json:"duration,omitempty"`
}

func (m *IndicesRequest) Reset()         { *m = IndicesRequest{} }
func (m *IndicesRequest) String() string { return proto.CompactTextString(m) }
func (*IndicesRequest) ProtoMessage()    {}
func (*IndicesRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_ecdc6c2fb8d35c9c, []int{4}
}
func (m *IndicesRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *IndicesRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_IndicesRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *IndicesRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_IndicesRequest.Merge(m, src)
}
func (m *IndicesRequest) XXX_Size() int {
	return m.Size()
}
func (m *IndicesRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_IndicesRequest.DiscardUnknown(m)
}

var xxx_messageInfo_IndicesRequest proto.InternalMessageInfo

func (m *IndicesRequest) GetLocation() string {
	if m != nil {
		return m.Location
	}
	return ""
}

func (m *IndicesRequest) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *IndicesRequest) GetDuration() string {
	if m != nil {
		return m.Duration
	}
	return ""
}

type IndicesResponse struct {
	Result string `protobuf:"bytes,1,opt,name=Result,json=result,proto3" json:"result,omitempty"`
}

func (m *IndicesResponse) Reset()         { *m = IndicesResponse{} }
func (m *IndicesResponse) String() string { return proto.CompactTextString(m) }
func (*IndicesResponse) ProtoMessage()    {}
func (*IndicesResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_ecdc6c2fb8d35c9c, []int{5}
}
func (m *IndicesResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *IndicesResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_IndicesResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *IndicesResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_IndicesResponse.Merge(m, src)
}
func (m *IndicesResponse) XXX_Size() int {
	return m.Size()
}
func (m *IndicesResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_IndicesResponse.DiscardUnknown(m)
}

var xxx_messageInfo_IndicesResponse proto.InternalMessageInfo

func (m *IndicesResponse) GetResult() string {
	if m != nil {
		return m.Result
	}
	return ""
}

func init() {
	proto.RegisterType((*ForecastRequest)(nil), "proto.ForecastRequest")
	proto.RegisterType((*ForecastResponse)(nil), "proto.ForecastResponse")
	proto.RegisterType((*NowRequest)(nil), "proto.NowRequest")
	proto.RegisterType((*NowResponse)(nil), "proto.NowResponse")
	proto.RegisterType((*IndicesRequest)(nil), "proto.IndicesRequest")
	proto.RegisterType((*IndicesResponse)(nil), "proto.IndicesResponse")
}

func init() { proto.RegisterFile("proto/weather.proto", fileDescriptor_ecdc6c2fb8d35c9c) }

var fileDescriptor_ecdc6c2fb8d35c9c = []byte{
	// 437 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x92, 0x41, 0x8b, 0xd3, 0x40,
	0x14, 0x80, 0x3b, 0xdd, 0xb5, 0x5b, 0x47, 0xd8, 0x5d, 0xc7, 0x75, 0xed, 0x06, 0x4d, 0x64, 0x14,
	0x91, 0xa5, 0x24, 0xd8, 0x7a, 0xaa, 0x07, 0x4b, 0x11, 0x41, 0xd0, 0x1e, 0x8a, 0xe0, 0xc9, 0x43,
	0x9a, 0x4e, 0xd3, 0x40, 0x9b, 0x17, 0x93, 0x89, 0x21, 0x57, 0x7f, 0x81, 0xe0, 0xcd, 0x93, 0x3f,
	0xc7, 0x63, 0xc1, 0x8b, 0xa7, 0x22, 0xad, 0xa7, 0xfe, 0x0a, 0xc9, 0xcc, 0xa4, 0x4d, 0xdb, 0x8b,
	0xb4, 0xa7, 0xc9, 0x7c, 0xbc, 0xf7, 0xbd, 0x37, 0x2f, 0x0f, 0xdf, 0x09, 0x42, 0xe0, 0x60, 0x25,
	0xcc, 0xe6, 0x23, 0x16, 0x9a, 0xe2, 0x46, 0x6e, 0x88, 0x43, 0xbb, 0xef, 0x02, 0xb8, 0x63, 0x66,
	0xd9, 0x81, 0x67, 0xd9, 0xbe, 0x0f, 0xdc, 0xe6, 0x1e, 0xf8, 0x91, 0x0c, 0xd2, 0x9e, 0xbb, 0x1e,
	0x1f, 0xc5, 0x7d, 0xd3, 0x81, 0x89, 0xe5, 0x82, 0x0b, 0x96, 0xc0, 0xfd, 0x78, 0xd8, 0xfe, 0xfc,
	0xcc, 0x6c, 0x9a, 0x0d, 0x01, 0xa5, 0x3d, 0xfb, 0x92, 0x59, 0x34, 0xc5, 0x67, 0xaf, 0x21, 0x64,
	0x8e, 0x1d, 0xf1, 0x1e, 0xfb, 0x14, 0xb3, 0x88, 0x93, 0x06, 0xae, 0xbe, 0x05, 0x47, 0xb8, 0x6b,
	0xe8, 0x21, 0x7a, 0x7a, 0xb3, 0x73, 0xb9, 0x9c, 0x19, 0x64, 0xac, 0x58, 0x1d, 0x26, 0x1e, 0x67,
	0x93, 0x80, 0xa7, 0xbd, 0x6a, 0xce, 0xb2, 0x9c, 0x57, 0x71, 0x28, 0x73, 0xca, 0xeb, 0x9c, 0x81,
	0x62, 0xc5, 0x9c, 0x9c, 0xd1, 0x36, 0x3e, 0x5f, 0x97, 0x8e, 0x02, 0xf0, 0x23, 0x46, 0xea, 0xb8,
	0xd2, 0x63, 0x51, 0x3c, 0xe6, 0xaa, 0xf2, 0xc5, 0x72, 0x66, 0x9c, 0x87, 0x82, 0x14, 0x1c, 0x15,
	0x49, 0x68, 0x1b, 0xe3, 0x2e, 0x24, 0x07, 0xf4, 0x4d, 0x5f, 0xe0, 0x5b, 0xc2, 0xb0, 0x57, 0xf9,
	0x1f, 0x08, 0x9f, 0xbe, 0xf1, 0x07, 0x9e, 0xc3, 0xa2, 0x43, 0x66, 0xf7, 0x04, 0x1f, 0xbf, 0x4f,
	0x03, 0xa6, 0xe6, 0x46, 0x96, 0x33, 0xe3, 0x94, 0xa7, 0x01, 0x2b, 0xc4, 0x1e, 0x67, 0xf7, 0x8d,
	0x19, 0x1f, 0xfd, 0xe7, 0x8c, 0x5f, 0xe2, 0xb3, 0x55, 0x87, 0xfb, 0xbc, 0xb1, 0xf1, 0xbd, 0x8c,
	0x4f, 0x3e, 0xc8, 0x65, 0x24, 0x1f, 0xf1, 0x89, 0x92, 0x91, 0xbb, 0x72, 0x7d, 0xcc, 0xcd, 0xe7,
	0x6b, 0x97, 0xdb, 0x58, 0xd6, 0xa4, 0x8f, 0xbe, 0xfc, 0xfa, 0xfb, 0xad, 0xfc, 0x80, 0xd6, 0xf2,
	0xc5, 0x5e, 0x9d, 0x9e, 0x8c, 0x6c, 0xa1, 0x6b, 0xf2, 0x0e, 0x1f, 0x75, 0x21, 0x21, 0xb7, 0x95,
	0x63, 0xfd, 0x67, 0x35, 0x52, 0x44, 0x4a, 0x69, 0x08, 0xe5, 0x15, 0xbd, 0xd8, 0x51, 0xfa, 0x90,
	0x64, 0x3a, 0x1b, 0x57, 0xf3, 0xf5, 0x22, 0x79, 0x5f, 0x5b, 0xab, 0xae, 0xdd, 0xdb, 0xe1, 0xca,
	0xfe, 0x58, 0xd8, 0x75, 0x7a, 0xb5, 0x63, 0x1f, 0xaa, 0xd0, 0x16, 0xba, 0xee, 0xd4, 0x7e, 0xce,
	0x75, 0x34, 0x9d, 0xeb, 0xe8, 0xcf, 0x5c, 0x47, 0x5f, 0x17, 0x7a, 0x69, 0xba, 0xd0, 0x4b, 0xbf,
	0x17, 0x7a, 0xa9, 0x5f, 0x11, 0xde, 0xe6, 0xbf, 0x00, 0x00, 0x00, 0xff, 0xff, 0x6f, 0x08, 0xc7,
	0x16, 0xcf, 0x03, 0x00, 0x00,
}

func (m *ForecastRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *ForecastRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *ForecastRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Duration) > 0 {
		i -= len(m.Duration)
		copy(dAtA[i:], m.Duration)
		i = encodeVarintWeather(dAtA, i, uint64(len(m.Duration)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Location) > 0 {
		i -= len(m.Location)
		copy(dAtA[i:], m.Location)
		i = encodeVarintWeather(dAtA, i, uint64(len(m.Location)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *ForecastResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *ForecastResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *ForecastResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Result) > 0 {
		i -= len(m.Result)
		copy(dAtA[i:], m.Result)
		i = encodeVarintWeather(dAtA, i, uint64(len(m.Result)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *NowRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *NowRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *NowRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Location) > 0 {
		i -= len(m.Location)
		copy(dAtA[i:], m.Location)
		i = encodeVarintWeather(dAtA, i, uint64(len(m.Location)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *NowResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *NowResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *NowResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Result) > 0 {
		i -= len(m.Result)
		copy(dAtA[i:], m.Result)
		i = encodeVarintWeather(dAtA, i, uint64(len(m.Result)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *IndicesRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *IndicesRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *IndicesRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Duration) > 0 {
		i -= len(m.Duration)
		copy(dAtA[i:], m.Duration)
		i = encodeVarintWeather(dAtA, i, uint64(len(m.Duration)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.Type) > 0 {
		i -= len(m.Type)
		copy(dAtA[i:], m.Type)
		i = encodeVarintWeather(dAtA, i, uint64(len(m.Type)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Location) > 0 {
		i -= len(m.Location)
		copy(dAtA[i:], m.Location)
		i = encodeVarintWeather(dAtA, i, uint64(len(m.Location)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *IndicesResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *IndicesResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *IndicesResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Result) > 0 {
		i -= len(m.Result)
		copy(dAtA[i:], m.Result)
		i = encodeVarintWeather(dAtA, i, uint64(len(m.Result)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintWeather(dAtA []byte, offset int, v uint64) int {
	offset -= sovWeather(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *ForecastRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Location)
	if l > 0 {
		n += 1 + l + sovWeather(uint64(l))
	}
	l = len(m.Duration)
	if l > 0 {
		n += 1 + l + sovWeather(uint64(l))
	}
	return n
}

func (m *ForecastResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Result)
	if l > 0 {
		n += 1 + l + sovWeather(uint64(l))
	}
	return n
}

func (m *NowRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Location)
	if l > 0 {
		n += 1 + l + sovWeather(uint64(l))
	}
	return n
}

func (m *NowResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Result)
	if l > 0 {
		n += 1 + l + sovWeather(uint64(l))
	}
	return n
}

func (m *IndicesRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Location)
	if l > 0 {
		n += 1 + l + sovWeather(uint64(l))
	}
	l = len(m.Type)
	if l > 0 {
		n += 1 + l + sovWeather(uint64(l))
	}
	l = len(m.Duration)
	if l > 0 {
		n += 1 + l + sovWeather(uint64(l))
	}
	return n
}

func (m *IndicesResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Result)
	if l > 0 {
		n += 1 + l + sovWeather(uint64(l))
	}
	return n
}

func sovWeather(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozWeather(x uint64) (n int) {
	return sovWeather(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *ForecastRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowWeather
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: ForecastRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: ForecastRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Location", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowWeather
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthWeather
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthWeather
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Location = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Duration", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowWeather
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthWeather
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthWeather
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Duration = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipWeather(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthWeather
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *ForecastResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowWeather
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: ForecastResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: ForecastResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Result", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowWeather
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthWeather
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthWeather
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Result = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipWeather(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthWeather
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *NowRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowWeather
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: NowRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: NowRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Location", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowWeather
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthWeather
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthWeather
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Location = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipWeather(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthWeather
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *NowResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowWeather
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: NowResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: NowResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Result", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowWeather
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthWeather
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthWeather
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Result = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipWeather(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthWeather
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *IndicesRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowWeather
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: IndicesRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: IndicesRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Location", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowWeather
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthWeather
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthWeather
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Location = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Type", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowWeather
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthWeather
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthWeather
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Type = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Duration", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowWeather
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthWeather
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthWeather
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Duration = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipWeather(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthWeather
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *IndicesResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowWeather
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: IndicesResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: IndicesResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Result", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowWeather
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthWeather
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthWeather
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Result = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipWeather(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthWeather
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipWeather(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowWeather
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowWeather
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowWeather
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthWeather
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupWeather
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthWeather
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthWeather        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowWeather          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupWeather = fmt.Errorf("proto: unexpected end of group")
)
